services:
  postgres:
    image: postgres:16-alpine
    container_name: aguafix-db
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - aguafix_pg_data:/var/lib/postgresql/data

volumes:
  aguafix_pg_data:
